module.exports = [
  { "id": "cph-as485", "name": "Alexander Jacob Ingemann Sarson" },
  { "id": "cph-as484", "name": "Allan Bo Simonsen" },
  { "id": "cph-ap294", "name": "Andreas Petersen" },
  { "id": "cph-at191", "name": "Aske Thor Thorsen" },
  { "id": "cph-bp133", "name": "Benjamin Paepke" },
  { "id": "cph-cb342", "name": "Cahit Bakirci" },
  { "id": "cph-ch465", "name": "Caroline Lærke Høg-Iversen" },
  { "id": "cph-cp277", "name": "Casper Prejler" },
  { "id": "cph-ck209", "name": "Christian Ambjørn Kehr" },
  { "id": "cph-cf124", "name": "Claus Mikkelsen Findinge" },
  { "id": "cph-ft36", "name": "Frederik Elbo Thorup" },
  { "id": "cph-fb87", "name": "Frederik Reimers Braagaard" },
  { "id": "cph-jb361", "name": "Jens Ohlendorff Brønd" },
  { "id": "cph-mb346", "name": "Mads Bredal Brandt" },
  { "id": "cph-mw202", "name": "Malthe Stefan Woschek" },
  { "id": "cph-mj734", "name": "Marcus Ekstrøm Johnsen" },
  { "id": "cph-mb604", "name": "Martin Laurvig Brandstrup" },
  { "id": "cph-mk584", "name": "Michael Nicolaj Korsgaard" },
  { "id": "cph-ml596", "name": "Mikkel Skott Lind" },
  { "id": "cph-nl163", "name": "Nina Lisakowski" },
  { "id": "cph-ol38", "name": "Oscar Nils Laurberg" },
  { "id": "cph-ry6", "name": "Rikke Elnif Manniche Yoon" },
  { "id": "cph-sa343", "name": "Søren Due Andersen" },
  { "id": "cph-tb193", "name": "Tobias Anker Boldt-Jørgensen" }
]